
server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true



spring:
  datasource:
    url: jdbc:mariadb://13.125.206.96:3306/econrich
    driver-class-name: org.mariadb.jdbc.Driver
    username: econrich
    password: econrich
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    '[shop.mtcoding.bank]': TRACE

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha